import LegalPageLayout from "../components/LegalPageLayout";

const content = {
  ko: `## 2. 개인정보 처리방침\n\n**개인정보 처리방침**\n\n**2.1 수집하는 정보**\n\n계정 정보: 이름, 이메일, 비밀번호(암호화), 직책, 소속 그룹\n\n서비스 이용 정보: 미팅 내용(사용자 직접 입력), 생성된 CPS/PRD/설계 문서, 크레딧 사용 내역, 서비스 접근 로그\n\n결제 정보: 결제 정보는 Paddle이 처리하며 FlowFD는 저장하지 않습니다. FlowFD는 Paddle Customer ID와 Subscription ID만 저장합니다.\n\n자동 수집 정보: IP 주소, 브라우저 정보, 접근 시간\n\n**2.2 정보 이용 목적**\n- 서비스 제공 및 개선\n- AI 파이프라인 실행 (미팅 → CPS → PRD → 설계)\n- 결제 및 구독 관리\n- 고객 지원 및 서비스 오류 분석\n\n**2.3 제3자 제공**\nFlowFD는 다음 경우에만 정보를 제3자에게 제공합니다:\n- **Paddle**: 결제 처리 (결제 관련 정보만)\n- **Google (Gemini API)**: AI 처리를 위해 미팅 내용 전송 — Google의 데이터 처리 정책 적용\n- **Firebase (Google)**: 인증 및 데이터 저장\n- **법적 요구**: 법원 명령 등 법적 의무가 있는 경우\n\n⚠️ 중요: 미팅 내용은 AI 처리를 위해 Google Gemini API 서버로 전송됩니다. 민감한 기업 정보 입력 시 이 점을 고려해주세요.\n\n**2.4 데이터 보관 기간**\n- 계정 정보: 계정 삭제 시까지\n- 미팅 및 문서: 프로젝트 또는 계정 삭제 시\n- 결제 내역: 법적 의무에 따라 5년\n\n**2.5 사용자 권리**\n데이터 열람, 수정, 삭제를 요청할 수 있습니다. 계정 설정에서 직접 삭제하거나 wb.hands.dev@gmail.com으로 문의하세요.\n\n**2.6 쿠키**\n로그인 세션 유지를 위한 필수 쿠키만 사용합니다. 광고 목적의 쿠키는 사용하지 않습니다.\n\n**2.7 보안**\n데이터는 HTTPS로 암호화 전송되며, Firebase Security Rules로 접근을 제어합니다.`,
  en: `## 2. Privacy Policy\n\n**Privacy Policy**\n\n**2.1 Information We Collect**\n\nAccount information: Name, email address, password (encrypted), job title, group membership\n\nService usage data: Meeting content (user-entered), generated CPS/PRD/design documents, credit usage history, access logs\n\nPayment information: Payment details are handled by Paddle — FlowFD does not store them. FlowFD only stores your Paddle Customer ID and Subscription ID.\n\nAutomatically collected: IP address, browser information, access timestamps\n\n**2.2 How We Use Your Information**\n- Providing and improving the service\n- Running the AI pipeline (Meeting → CPS → PRD → Design)\n- Managing payments and subscriptions\n- Customer support and error analysis\n\n**2.3 Third-Party Sharing**\nFlowFD shares information with third parties only in the following cases:\n- **Paddle**: Payment processing (payment-related data only)\n- **Google (Gemini API)**: Meeting content is sent to Google's servers for AI processing — Google's data processing terms apply\n- **Firebase (Google)**: Authentication and data storage\n- **Legal requirements**: When required by court order or other legal obligations\n\n⚠️ Important: Your meeting content is transmitted to Google Gemini API servers for AI processing. Please consider this when entering sensitive business information.\n\n**2.4 Data Retention**\n- Account information: Until account deletion\n- Meeting data and documents: Until project or account deletion\n- Payment records: 5 years as required by law\n\n**2.5 Your Rights**\nYou may request access to, correction of, or deletion of your data. Use account settings to delete directly, or contact wb.hands.dev@gmail.com.\n\n**2.6 Cookies**\nWe use only essential cookies for maintaining login sessions. No advertising cookies are used.\n\n**2.7 Security**\nAll data is transmitted via HTTPS encryption. Access is controlled through Firebase Security Rules.\n`,
};

export const metadata = {
  title: "개인정보처리방침 | FlowFD",
  description: "FlowFD 개인정보 처리방침",
};

export default function PrivacyPage() {
  return <LegalPageLayout content={content} currentHref="/privacy" />;
}
